version: "3.9"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.local
    container_name: app-proxy-local
    ports:
      - "4444:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped