version: "3.9"

services:
  nginx:
    image: nginx:stable
    container_name: app-proxy-local
    volumes:
      - ./nginx/default.local.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "4444:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped